layout_spectrum: 0.3901282
typography_spectrum: 0.9832705
color:
  lightness: 0.08297241
  brandStrength: 0.9041017
  saturation: 0.4097824
  rhythmicContrast: 0.1184426
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: 'Recycle Vanuatu '
