name: 'Recycle Vanuatu '
favicon: null
layout_spectrum: 0.912766
typography_spectrum: 0.1255319
title: Vanuatu test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#92d5c4'
    - '#58a3ac'
    - '#f32c33'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
