name: 'Recycle Vanuatu '
favicon: null
layout_spectrum: 0.75638
typography_spectrum: 0.19176
title: Vanuatu test recycling plan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#92d5c4'
    - '#58a3ac'
    - '#f32c33'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
